<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3xfjsri\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3xfjsri/appProdProjectContainer.php') {
    touch(__DIR__.'/Container3xfjsri.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container3xfjsri\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container3xfjsri\appProdProjectContainer([
    'container.build_hash' => '3xfjsri',
    'container.build_id' => 'a9dbf0d2',
    'container.build_time' => 1614717138,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3xfjsri');
