<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFwnfve3\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFwnfve3/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerFwnfve3.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerFwnfve3\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerFwnfve3\appProdProjectContainer([
    'container.build_hash' => 'Fwnfve3',
    'container.build_id' => '2b392349',
    'container.build_time' => 1569567866,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFwnfve3');
