<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSndndmv\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSndndmv/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerSndndmv.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerSndndmv\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerSndndmv\appProdProjectContainer([
    'container.build_hash' => 'Sndndmv',
    'container.build_id' => 'fd26b0de',
    'container.build_time' => 1567141388,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSndndmv');
