<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8gwzz4c\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8gwzz4c/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container8gwzz4c.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container8gwzz4c\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container8gwzz4c\appDevDebugProjectContainer([
    'container.build_hash' => '8gwzz4c',
    'container.build_id' => '0d4c5e50',
    'container.build_time' => 1623575301,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8gwzz4c');
